### ISSUE TITLE
Support schemeless urls

### ISSUE THREAD

**Issue by matthijskooijman** [cltrudeau/django-airplane#3]
It would be nice to support schemeless urls. When these urls appear in HTML, they will automatically copy the scheme (http or https) from the page they appear in, to allow http requests when possible, and using https request (and preventing mixed content warnings) when the page is https.

E.g. the following currently fails to parse the url:

    <script src="{% airplane "//code.jquery.com/jquery-3.4.1.min.js" %}"></script>

**Comment by cltrudeau** [comment]
I'm interested in your thoughts on solving this. The problem is within the template tag you don't have access to the requests object, which is where you would normally get the schema. I can make assumptions about http or https, but that might be fragile. 

When I've written code like this before I've always had a setting that stored the schema, but I don't want to force that pattern on other people.

I haven't be doing a lot of django lately. Maybe in the newer versions this information is somewhere else? Open to ideas.

**Comment by matthijskooijman** [comment]
> I'm interested in your thoughts on solving this. The problem is within the template tag you don't have access to the requests object, which is where you would normally get the schema. I can make assumptions about http or https, but that might be fragile.

Ah, good point. OTOH, since you'll be making a request in the background, it does not actually matter whether the scheme matches the request itself. Also, if you use //, it is *probably* safe to assume that both http and https are *available*, and then defaulting to https is probably safe?

**Comment by cltrudeau** [comment]
I've done a naive implementation that assumes https for schemaless. Thank again for your interest. You should be able to "pip install django-airplane" and get the 1.0 version with all your suggestions.

**Comment by matthijskooijman** [comment]
Just testes this, works like a charm (also the AUTO_MODE). Thanks for the quick followup! :-D
